server:
  port: 8762

spring:
  application:
    name: EDGE-SERVICE
#
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


USER_PATH: /user
ADMIN_PATH: /admin
PERMIT_ALL_PATH: /home

# following constants are for validation of various Json inputs and Exception handling.
UM_EXCEPTION: UM Exception
VALIDATION_FAILED: Validation Failed
